finish game implementation
YESENIA2012/TRIKI-GAME pull request #2
Opened 2021-12-18 21:26 UTC by YESENIA2012

2021-12-18 22:21 UTC, YESENIA2012 commented
* change 1: The inline-block display was removed from the row class and placed in the column class
* change 2: add h3 tag in html file to expose winning player
* change 3: a js file called utils was created, where the function that draws the game table is found and is inserted into the html
* change 4: in the utils file a function is implemented that goes through the diagonals and looks for if there is a winner in them
* change 5: in the utils file a function is implemented that goes through the rows and searches if there is a winner in them
* change 6: in the utils file a function is implemented that goes through the columns and looks for if there is a winner in them
* change 6: the name of the array is changed to scores

2022-01-16 22:53 UTC, erick2014 requested changes

2022-01-16 22:53 UTC, erick2014 commented on creatingGame.js
> +  let game = drawGame(numRows, numColumns);
rename the `game` variable to `dashboardGame` . Also rename the variable on lines 23, 24

2022-01-16 22:53 UTC, erick2014 commented on creatingGame.js
> +    let atributosImagen = imagen.getAttribute("class");
this variable, should be const, and should be translate to english: `imageAttributes`

2022-01-16 22:53 UTC, erick2014 commented on creatingGame.js
>      let imagen = evento.target;
this should not be **let** but **constant** and should be name in english: `const image = event.target`

2022-01-16 22:53 UTC, erick2014 commented on creatingGame.js
> +  let numRows = document.getElementById("filas").value;
rename this variable to `rowsNumber`. Please translate all variables from spanish to english.

2022-01-16 22:53 UTC, erick2014 commented on creatingGame.js
> +  let numColumns = document.getElementById("columnas").value;
rename this variable to `columnsNumber`

2022-01-16 22:53 UTC, erick2014 commented on creatingGame.js
>    var turno = jugador1;
turno should be in english: `player=player1`

2022-01-17 01:01 UTC, erick2014 requested changes

2022-01-17 01:01 UTC, erick2014 commented on creatingGame.js
create a function ( in utils.js file) that creates these two texts. Just call the functions twice and pass each text that is going to be for each player.

2022-03-30 03:10 UTC, merged